- name: Install package on system
  ansible.builtin.include_tasks: "pkg-{{ ansible_pkg_mgr }}.yml"

- name: Enable nftables service
  ansible.builtin.systemd:
    name: nftables
    enabled: true

- name: Create /etc/nftables dir
  ansible.builtin.file:
    path: /etc/nftables
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate nftables config
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: "/{{ item.path | regex_replace('\\.j2$', '') }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop: "{{ q('community.general.filetree', 'templates/') }}"
  notify: restart nftables
  when: item.state in ('file', 'link')
  tags:
    config
